# backendrefs is for upstream: traffic between the rout and the service
# Terminate is what we need to terminate the session on the gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-https-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "whatever.com"
  rules:
  - backendRefs:
    - name: nginxgw
      port: 443
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
